### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by ollietreend** [davidsteinsland/cakephp-gearman#2]
Hi

I'm interested in using this plugin for a CakePHP 2 app that I'm working on.

I can see that this project hasn't been worked on in a couple of years now. Neither does it seem to have a very active community around it.

Is this one of those things that 'just works' and therefore there hasn't been a need to add extra features, fix bugs, etc? Or is this no longer in active use/development?

If this project is dead, do you have any recommendations on alternative setups? I like the idea of working with gearman, but am open to alternative methods of integrating it into my CakePHP app.

Thanks

**Comment by davidsteinsland** [comment]
Hi!

I haven't worked on the project as I haven't discovered any bugs yet. As far as I'm aware, it *just works*. I used it a couple of times without hazzle.

**Comment by ollietreend** [comment]
Great! That sounds promising.

Thanks!
